version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"          # raíz del repo
    schedule:
      interval: "weekly"    # o "daily" si quieres revisiones más frecuentes
    open-pull-requests-limit: 5
    update-types:
      - "version-update:semver-patch"
      - "version-update:semver-minor"
    ignore:
      - dependency-name: "esbuild"  # si quieres ignorar la que daba error
