version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"          # La raíz de tu proyecto
    schedule:
      interval: "weekly"    # Cambia a "daily" si quieres
    allow:
      - dependency-type: "direct"   # Solo dependencias directas
    ignore:
      - dependency-name: "tar-fs"   # Ignora dependencias transitivas problemáticas
      - dependency-name: "esbuild"
