version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"  # RaÃ­z del repositorio
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "vue-template-compiler"
        versions:
          - ">=3.0.0"  # Ignorar versiones incompatibles con Vue 3 / Nuxt 3
    commit-message:
      prefix: "chore(deps):"
